### ISSUE TITLE
Testing my issues

### ISSUE THREAD

**Issue by StephenGitHuber** [Sienci-Labs/Resources#3]
Test for comments
![Nut Assemblies](https://github.com/user-attachments/assets/e0e5fdd0-a81a-4c7d-bd98-91488a52b497)

**Comment by SienciLabs** [comment]
Yeah that's a good idea to update, do you think it should be this line?
https://github.com/Sienci-Labs/Resources/blob/e3fa841caa9f3aa455a0c3d482f9949744286c56/superlongboard/slb-troubleshooting-test.md?plain=1#L30-L34

**Comment by SienciLabs** [comment]
Thanks

**Comment by SienciLabs** [comment]
Thanks
